### ISSUE TITLE
missing the empty_template folder within template_files

### ISSUE THREAD

**Issue by skdunnigan** [StormStories/SWMPr_Storm_Story_Template#2]
@benjamincrary just curious. we have had some folks try to create the PowerPoint file with the template repository, but when they run that script, they encounter:

Error: could not find file "template_files/empty_template/Storm_Story_Template.pptx"

Is this a file that was supposed to be in the repository or is it generated through the script somewhere and a step was missed?

**Comment by skdunnigan** [comment]
It looks like in the most recent commit in May (https://github.com/StormStories/SWMPr_Storm_Story_Template/commit/ab395bd020dbe498bd2e0c9f43d35e4daf1d2f99) that the empty_template folder and that .pptx file were deleted.

**Comment by benjamincrary** [comment]
Hi @skdunnigan - not sure why the template was removed, but nonetheless, I've added the template file in commit [447b0a5](https://github.com/StormStories/SWMPr_Storm_Story_Template/commit/447b0a52d84c789c29c4a32dfbb0424dc4ab4690)
